name: "Helm Chart Releaser Action"
description: |
  A GitHub Action for packaging and releasing Helm charts.
  This action uses Helm package and Helm push to package and release your charts.
  The action will tag the commit with the chart version.
inputs:
  gh_token:
    description: |
      Permission token that grants permission to the GitHub API.
      This is used to tag the commit with the chart version.
    required: true
  github_actor:
    description: |
      The GitHub actor to use when tagging the commit with the chart version.
      This is used to configure Git.
    required: false
    default: ${{ github.actor }}
  charts_dir:
    description: 'The directory containing the Helm charts to package and release.'
    required: false
    default: "charts"
  chart_repository_url:
    description: |
      The URL of the chart repository to release the charts to.
      This is used to configure the Helm push plugin.
      Example: oci://ghcr.io/username/repo
    required: true
  chart_repository_username:
    description: |
      The username to use when authenticating to the chart repository.
      This is used to configure the Helm push plugin.
    required: true
  chart_repository_password:
    description: |
      The password to use when authenticating to the chart repository.
      This is used to configure the Helm push plugin.
    required: true
branding:
  icon: 'terminal'
  color: 'blue'
runs:
  using: docker
  image: Dockerfile
  env:
    GITHUB_TOKEN: ${{ inputs.gh_token }}
    CHARTS_DIR: ${{ inputs.charts_dir }}
    CHART_REPOSITORY: ${{ inputs.chart_repository_url }}
    CHART_REPOSITORY_USERNAME: ${{ inputs.chart_repository_username }}
    CHART_REPOSITORY_PASSWORD: ${{ inputs.chart_repository_password }}
    GH_ACTOR: ${{ inputs.github_actor }}
