name: "Helm Chart Releaser Action"
description: |
  A GitHub Action for packaging and releasing Helm charts.
  This action uses Helm package and Helm push to package and release your charts.
  The action will tag the commit with the chart version.
inputs:
  gh_token:
    description: |
      Permission token that grants permission to the GitHub API.
      This is used to tag the commit with the chart version.
    required: true
  github_actor:
    description: |
      The GitHub actor to use when tagging the commit with the chart version.
      This is used to configure Git.
    required: false
    default: ${{ github.actor }}
  charts_dir:
    description: 'The directory containing the Helm charts to package and release.'
    required: false
    default: "charts"
  chart_repository_url:
    description: |
      The URL of the chart repository to release the charts to.
      This is used to configure the Helm push plugin.
      Example: oci://ghcr.io/username/repo
    required: true
  chart_repository_username:
    description: |
      The username to use when authenticating to the chart repository.
      This is used to configure the Helm push plugin.
    required: true
  chart_repository_password:
    description: |
      The password to use when authenticating to the chart repository.
      This is used to configure the Helm push plugin.
    required: true
branding:
  icon: 'terminal'
  color: 'blue'
runs:
  using: "composite"
  steps:
    - name: Add GitHub token to env
      shell: bash
      run: echo "GITHUB_TOKEN=${{ inputs.gh_token }}" >> $GITHUB_ENV

    - name: Configure Git
      shell: bash
      run: |
        git config user.name "${{ inputs.github_actor }}"
        git config user.email "${{ inputs.github_actor }}@users.noreply.github.com"

    - name: Install Helm
      uses: azure/setup-helm@v3

    - name: Login to Helm registry
      shell: bash
      run: |
        echo "${{ inputs.chart_repository_password }}" | \
        helm registry login $(echo ${{ inputs.chart_repository_url }} | cut -d'/' -f3-4) \
          --username ${{ inputs.chart_repository_username }} \
          --password-stdin

    - name: Debug
      shell: bash
      run: |
        echo "===== Current dir ====="
        ls -l
        echo "===== current dir -> charts dir ====="
        ls -l ${{ inputs.charts_dir }}
        echo "===== Action path ====="
        ls -l ${{ github.action_path }}
        echo "===== Action path charts dir ====="
        ls -l ${{ github.action_path }}/${{ inputs.charts_dir }}

    - name: Build and push Helm charts
      working-directory: ${{ github.action_path }}
      env:
        GITHUB_TOKEN: ${{ inputs.gh_token }}
        CHARTS_DIR: ${{ inputs.charts_dir }}
        CHART_REPOSITORY: ${{ inputs.chart_repository_url }}
      shell: bash
      run: ${{ github.action_path }}/entrypoint.sh

    - name: Logout from Helm registry
      if: always()
      shell: bash
      run: |
        helm registry logout $(echo ${{ inputs.chart_repository_url }} | cut -d'/' -f3-4)
